dictionary/urls.py
from django.conf.urls import url

from . import views

app_name = 'dictionary'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^stage/$', views.stage_area, name='stage_area'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^letter/$', views.letter, name='letter'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^login_page/$', views.login_page, name='login_page'),
    url(r'^word/(?P<word>.+)/', views.detail_word, name='detail_word'),
    url(r'^accept/(?P<id>\d+)/$', views.accept, name='accept'),
    url(r'^submit/(?P<id_word>[0-9]+)/$', views.submit_word, name='submit_word'),
    url(r'^letter/(?P<lang>[A-Za-z-]+)/$', views.letter, name='letter'),
    url(r'^refuse/(?P<id>\d+)/(?P<redirect>[A-Za-z-]+)/$', views.refuse, name='refuse'),
]

ifal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^dictionary/', include('dictionary.urls')),
    url(r'^admin/', admin.site.urls),
]

dictionary/models.py
from django.db import models

class Language(models.Model):
    language = models.CharField(max_length=5, primary_key=True)
    alphabet = models.CharField(max_length=50)

    def __str__(self):
        return "{0}".format(self.language)

class Word(models.Model):
    language   = models.ForeignKey(Language, on_delete=models.CASCADE)
    id_word    = models.IntegerField()
    term       = models.CharField(max_length=30)
    definition = models.CharField(max_length=150)
    category   = models.CharField(max_length=30)
    stage      = models.CharField(max_length=1, default='n')

    def __str__(self):
        return "({0} - {1}) {2}: {3}".format(self.id_word, self.language, self.term, self.definition)

dictionary/forms.py
from  django import forms
from .models import Language, Word

class WordForm(forms.Form):
    id_word    = forms.CharField(Word.objects.all().last().id_word + 1, widget=forms.HiddenInput)
    language   = forms.ModelChoiceField(queryset = Language.objects.all())
    term       = forms.CharField(max_length=30)
    definition = forms.CharField(max_length=150)
    category   = forms.ChoiceField(choices = ((1, ('hardware')), (2, ('concept')), (3, ('software'))))

dictionary/views.py
from .forms                          import WordForm
from .models                         import Word, Language
from  django.http                    import HttpResponse, HttpResponseRedirect
from  django.template                import loader
from  django.core.mail               import EmailMessage
from  django.shortcuts               import render
from  django.contrib.auth            import authenticate, login as auth_login, logout as auth_logout
from  django.contrib.auth.models     import User
from  django.contrib.auth.decorators import login_required

def detail_word(request, word=''):
    ids = list(set([obj.id_word for obj in Word.objects.filter(term=word, stage='n')]))
    template = loader.get_template('dictionary/detailWord.html')
    result = Word.objects.filter(id_word__in=ids, stage='n')
    words = [] # Agrupa as palavras de acordo com o id_word

    for key in ids:
        words += [[word for word in result if word.id_word == key]]

    template = loader.get_template('dictionary/detailWord.html')
    context = { 'title': word, 'words': words }

    return HttpResponse(template.render(context, request))

def login_page(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/dictionary/')

    template = loader.get_template('dictionary/login.html')
    context = { }

    return HttpResponse(template.render(context, request))

def contact(request):
    if request.method == 'POST':
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        email = EmailMessage("Contact from site", "Subject: {2}\nEmail from: {0}\n\nMessage: {1}".format(email, message, subject), to=['dictionarytechnical@gmail.com'])
        email.send()

        return HttpResponseRedirect('/dictionary/')
        
    context = { }
    template = loader.get_template('dictionary/contact.html')

    return HttpResponse(template.render(context, request))

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                auth_login(request, user)
                return HttpResponseRedirect('/dictionary/')
            else:
                return HttpResponse('Error sir :3')
        else:
            return HttpResponse("Invalid login details supplied.")

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/dictionary/')

def submit_word(request, id_word):
    template = loader.get_template('dictionary/submitWord.html')

    if request.method == 'GET':
        if id_word != '0':
            form = WordForm(initial={'language': 'en-us', 'id_word': id_word})
        else:
            form = WordForm(initial={'language': 'en-us', 'id_word': Word.objects.all().last().id_word + 1})
            
        return HttpResponse(template.render({'form': form }, request))
    else:
        form = WordForm(request.POST)

        if form.is_valid():
            new_word = Word.objects.create(language   = Language.objects.get(language=form.cleaned_data['language']),
                                           id_word    = form.cleaned_data['id_word'],
                                           term       = form.cleaned_data['term'],
                                           definition = form.cleaned_data['definition'],
                                           category   = form.cleaned_data['category'],
                                           stage      = 'y')

            new_word.save()

        return HttpResponse(template.render({}, request))

def index(request):
    languages = Language.objects.all()
    context = {'languages' : languages,}
    return render(request, 'dictionary/index.html', context)

def letter(request, lang='en-us'):
    word_list = Word.objects.filter(language=lang, stage='n').order_by('term')
    alphabet_list = Language.objects.get(language=lang)
    language_list = Language.objects.values('language')
    words = []

    for letter in list(alphabet_list.alphabet):
        words += [[word.term for word in word_list if word.term.lower()[0] == letter]]

    context = {
        'word_list': words,
        'alphabet_list': alphabet_list,
        'lang': lang,
        'language_list': language_list,
    }

    return render(request, 'dictionary/letter.html', context)

@login_required
def stage_area(request):
    words = Word.objects.filter(stage='y')
    context = { 'words': words, }
    template = loader.get_template('dictionary/stagearea.html')

    return HttpResponse(template.render(context, request))

@login_required
def accept(request, id):
    if request.user.is_authenticated():
        new_word = Word.objects.get(pk=id)
        old_word = Word.objects.filter(language=new_word.language, id_word=new_word.id_word, stage='n')

        if old_word.exists():
            old_word[0].delete()

        new_word.stage = 'n'
        new_word.save()

    return HttpResponseRedirect('/dictionary/stage')

# alterar para reconhecer a página anterior sem precisar dessa informação através da url
@login_required
def refuse(request, id, redirect):
    if redirect == 'stage':
        topage = '/dictionary/stage/'
    else:
        topage = "/dictionary/letter/{0}/".format(redirect)

    deleteWord(id)

    return HttpResponseRedirect(topage)

@login_required
def delete_word(id):
    word = Word.objects.get(pk=id)

    word.delete()

dictionary/templates/dictionary/base.html
<!DOCTYPE html>

<html lang="en-us">
<head>
    <meta charset="UTF-8" /> 
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="http://www.w3schools.com/lib/w3.css">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'dictionary/css/style.css' %}" />

    <script type="text/javascript">
        {% block javascript %}{% endblock %}
    </script>

    <script type="text/javascript">
        function dropUserOptions() {
            var x = document.getElementById("userNavDrop");
            if (x.className.indexOf("w3-show") == -1) {
                x.className += " w3-show";
            } else {
                x.className = x.className.replace(" w3-show", "");
            }
        }
    </script>
</head>
<body>
    <nav class="w3-top">
        <ul class="w3-navbar w3-green w3-card-2 w3-large">
            <li><a class="w3-teal" href="{% url 'dictionary:index' %}">Dictecnic</a></li>
            <li><a href="{% url 'dictionary:index' %}">Index</a></li>
            <li><a href="{% url 'dictionary:letter' 'en-us' %}">Alphabet</a></li>
            <li><a href="{% url 'dictionary:submit_word' 0 %}">Help us</a></li>
            <li><a href="{% url 'dictionary:contact' %}">Contact</a></li>
            {% if user.is_anonymous %}
            <li class='w3-right'><a href="{% url 'dictionary:login_page' %}">Login</a></li>
            {% else %}
            <li class="w3-right w3-dropdown-click">
                <a onclick="dropUserOptions()">{{user}}</a>
                <div id="userNavDrop" class="w3-dropdown-content w3-white w3-card-4 w3-animate-zoom dropdown">
                    <a class="w3-padding-16" href="{% url 'dictionary:stage_area' %}">Stage area</a>
                    <a class="w3-padding-16" href="{% url 'dictionary:logout' %}">Logout</a>
                </div>
            </li>
            {% endif %}
        </ul>
    </nav>

    <div class="content">
    {% block content %}{% endblock %}
    </div>

    <footer class="footer">
        <span>&copy; 2016 - Technical Dictionary</span>
    </footer>
</body>
</html>

dictionary/templates/dictionary/contact.html
{% extends 'dictionary/base.html' %}

{% block title %}Dictionary - Contact{% endblock %}

{% block content %}

<form method="post" action="{% url 'dictionary:contact' %}">
    {% csrf_token %}

    <label for="email">Email: </label>
    <input type="text" name="email" />
    <br /> <!-- Substituir por um display:block no futuro -->
    <label for="subject">Subject: </label>
    <input type="text" name="subject" />
    <br /> <!-- Substituir por um display:block no futuro -->
    <label for="message">Message: </label>
    <textarea name="message"></textarea>
    <br /> <!-- Substituir por um display:block no futuro -->
    <input type="submit" value="Send message &raquo;" />
</form>
{% endblock %}

dictionary/templates/dictionary/detailWord.html
{% extends "dictionary/base.html" %}

{% block title %}{{ title }}{% endblock %}


<script>
{% block javascript %}
    var words_json = 
    [
    {% for meaning in words %}
        [
        {% for word in meaning %}
            {"term": "{{ word.term }}", "language": "{{ word.language }}", "definition": "{{ word.definition }}"}

            {% if not forloop.last %}
            ,
            {% endif %}
        {% endfor %}
        ]

        {% if forloop.last %}
    ]
        {% else %}
        ,
        {% endif %}
{% endfor %}
    ;
function update(term, language, meaning) {
    var info = document.getElementById("id-div-" + meaning);
    var word;

    for (i = 0; i < words_json[parseInt(meaning)-1].length; i++) {
        word = words_json[parseInt(meaning)-1][i];

        if (word.term === term) {
            if (word.language === language) {
                break;
            }
        }
    }

    info.innerHTML = "<h2>" + word.term + "</h2>\n\n<p>" + word.definition + "</p>";
}
{% endblock %}
</script>

{% block content %}
<h1>{{ title }}</h1>

{% if words %}
    {% for group in words %}
        {% with meaning=forloop.counter %}
        <div>
            <p class="id-div-info">{{ forloop.counter }}</p>
            <ul>
                {% for word in group %}
                    <li>({{word.language}}) <a style="cursor: pointer" onclick='update("{{ word.term }}", "{{ word.language }}", "{{ meaning }}")'>{{word.term}}</a></li>
                    {% if not user.is_anonymous %}
                    <a href="{% url 'dictionary:refuse' word.id word.language %}">Delete</a>
                    {% endif %}
                    {% if forloop.last %}
                    <a href="{% url 'dictionary:submit_word' word.id_word %}">Submit a enhacement</a>
                    {% endif %}
                {% endfor %}
            </ul>
            <div id="id-div-{{ meaning }}">
                
            </div>
        </div>
        {% endwith %}
    {% endfor %}
{% else %}
    <p>No results.</p>
{% endif %}
{% endblock %}

dictionary/templates/dictionary/index.html
{% extends "dictionary/base.html" %}

<!DOCTYPE html>
<html>
<head>
	{% block title %}Dicionário - Busca{% endblock %}

	<script type="text/javascript">
		{% block javascript %}
		var l = [	{% for lang in languages.all %}{"language":"{{ lang.language }}", "alphabet":"{{ lang.alphabet }}"} {% if forloop.last %} ]; {% else %} , {% endif %}
		{% endfor %}

		function redirect() {
			var current_url = window.location.href;
			current_url += "word/" + document.getElementById("search-text").value;
			window.location.href = current_url;
		}

		function changeAlphabet() {
			var langSelect = document.getElementById("languageSelector").value;
			for (var i = 0; i < l.length; i++) {
				if (l[i].language == langSelect) {
					displayNewAlphabet(l[i].alphabet, langSelect);
					return;
				}
			}
		}

		function displayNewAlphabet (alphabet, lang) {
			var newDivAlphabet = "";

			for (var i = 0; i < alphabet.length; i++) {
				newDivAlphabet += "<a href=\"letter\/" + lang + "#" + alphabet[i] + "\">" + alphabet[i] + "<\/a> ";
			}

			document.getElementById("divAlphabet").innerHTML = newDivAlphabet;
		}

		window.onload = changeAlphabet;
		{% endblock %}
	</script>
</head>
<body >
	{% block content %}
	<div class="w3-container w3-padding-jumbo w3-padding-64">
		<!-- Logo -->
		<div class="w3-padding-top">
			{% load staticfiles %}
			<img src="{% static 'dictionary/images/logo.jpg' %}" class="w3-border w3-border-black w3-round-xxlarge">
		</div>

		<!--Área de pesquisa-->
		<div class="w3-row-padding w3-padding-top">
			<div class="w3-col m9 l9"><input class="w3-input w3-border w3-round" type="text" id="search-text" placeholder="Digite uma palavra"></div>
			<div class="w3-col m3 l3"><button class="w3-btn-block w3-green w3-round-large" id="searchButton" onclick="redirect()">Buscar</button></div>
		</div>
	</div>

	<!--Linguagens e alfabetos-->
	<select id="languageSelector" onchange="changeAlphabet()">
		{% for lang in languages.all %}
		<option>{{lang.language}}</option>
		{% endfor%}
	</select>

	<div id="divAlphabet"></div>
	{% endblock %}
</body>
</html>

dictionary/templates/dictionary/letter.html
{% extends "dictionary/base.html" %}

{% block title %}Letter{% endblock %}

<script>
{% block javascript %}
	function redirect(){
			languageSelected = document.getElementById('languageSelected').value;
                        window.location.href = "{% url 'dictionary:letter' %}" + languageSelected;
		}
{% endblock %}
</script>

{% block content %}
	<select id="languageSelected" onchange="redirect()">
		{% for a in language_list %}
			{% if a.language == lang %}
				<option value="{{ a.language }}" selected>{{ a.language }}</option>
			{% else %}
				<option value="{{ a.language }}">{{ a.language }}</option>
			{% endif %}
		{% endfor%}
	</select>

    {% if word_list %}
        <ul>
        {% for words in word_list %}
            {% if words %}
            <div>
            {% for word in words %}
                {% if forloop.first %}
                <h2 id="letter-{{ word | slice:":1" }}">{{ word | slice:":1" }}</h2>
                {% endif %}
                <li><a href="{% url 'dictionary:detail_word' word %}">{{ word }}</a></li>
            	{% endfor %}
            <div>
            {% endif %}
        {% endfor %}
        </ul>
    {% else %}
        <p>No words are available.</p>
    {% endif %}
{% endblock %}

dictionary/templates/dictionary/login.html
{% extends 'dictionary/base.html' %}

{% block title %}Dictionary - Login{% endblock %}

{% block content %}
<form id="login_form" method="post" action="{% url 'dictionary:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />

    <input type="submit" value="submit" />
</form>
{% endblock %}

dictionary/templates/dictionary/stagearea.html
{% extends "dictionary/base.html" %}

{% block title %}{{ title }}{% endblock %}

<script>
{% block javascript %}
    var words_json = 
        [
        {% for word in words %}
            {"term": "{{ word.term }}", "language": "{{ word.language }}", "definition": "{{ word.definition }}"}

            {% if not forloop.last %}
            ,
            {% endif %}
        {% endfor %}
        ]
    ;
{% endblock %}
</script>

{% block content %}
{% for word in words %}
<ul>
    <div>
        <li>({{ word.language }}) {{ word.term }}: {{ word.definition }}</li>
        <a href="{% url 'dictionary:accept' word.id %}">Accept</a>
        <a href="{% url 'dictionary:refuse' word.id 'stage' %}">Refuse</a>
    </div>
</ul>
{% endfor %}
{% endblock %}

dictionary/templates/dictionary/submitWord.html
{% extends "dictionary/base.html" %}

{% block title %}Help us!{% endblock %}

{% block content %}
{% if form %}
<h1>Submit a new translation</h1>

<form method="POST">
    {% csrf_token %} 
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% else %}
<h1>Thank you for your contribution</h1>
{% endif %}
{% endblock %}

dictionary/templates/index.html
<div>
	<h1><a href="#">Dictionary</a></h1>
</div>

{% if alphabet_list %}
    <ul>
    {% for a in alphabet_list %}
	    <div>
	        <li><a href="/dictionary/{{ a.language }}">{{ a.language }}</a></li>
		  	{% for i in a.alphabet|make_list %}
		  		<a href="/dictionary/{{ i }}">{{ i }}</a>
		  	{% endfor %}
		</div>
    {% endfor %}
{% else %}
    <p>No alphabets are available.</p>
{% endif %}